spring:
  profiles:
    active: dev
  # 格式化全局时间字段
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    # 指定时间区域类型
    time-zone: GMT+8
  jpa:
    show-sql: true
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger.json

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
mybatis:
  type-aliases-package: cn.pzhxy.devicemanager.*.domain,cn.pzhxy.devicemanager.*.query
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
auth:
  permission:
    controller-package: cn.pzhxy.devicemanager.org.controller,cn.pzhxy.devicemanager.auth.controller,cn.pzhxy.devicemanager.device.controller,cn.pzhxy.devicemanager.goods.controller,cn.pzhxy.devicemanager.notice.controller,cn.pzhxy.devicemanager.sys.controller,cn.pzhxy.devicemanager.record.controller,cn.pzhxy.devicemanager.seller.controller,cn.pzhxy.devicemanager.statistics.controller
backup:
  filePath: D:\\device_manager_system_backup\\
