server:
  port: 8080
spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    permission_system ronghuanet-crm
    url: jdbc:mysql://localhost:3306/pzhxy_device_manager?useSSL=false&characterEncoding=utf8
    username: root
    password: 199135

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/static/upload/headImage/
  servlet:
    multipart:
      # 文件上传的最大字节数，默认为1MB
      max-file-size: 10MB
      # 请求最大字节数，包括文件和表单数据，默认为10MB
      max-request-size: 20MB